<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>File upload failed</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <!-- use the font -->
    <style>
        body {
            font-family: 'Roboto', sans-serif;
        }

        .header {
            color: rgb(36, 140, 202);
        }

        .body {
            padding: 30px 30px 30px 30px;
            background-color: #eaeaea;
            height: 100%
        }

        .content {
            width: 80%;
            margin-left: 10%;
            margin-right: 10%;
            margin-bottom: 20px;
            padding: 20px;
        }

        .footer {
            padding: 15px 15px 15px 30px;
            background-color: #777777;
            font-size: 11px;
            width: 80%;
            margin-left: 10%;
            margin-right: 10%;
        }

        .email {
            font-size: 14px;
            font-weight: normal;
            padding: 20px 5px;
            border-style: solid;
            border-width: 0px;
            overflow: hidden;
            word-break: normal;
            border-color: #ccc;
            color: #333;
        }
    </style>
</head>
<body>
<div class="body">
    <h1 align="center" class="header">
        <img src="cid:logo.png" width="45" height="30" style="margin-bottom: -5px"/>
        LL Middleware
    </h1>


    <div class="content">
        <#list emails?keys as subject>
            <div class="email">
                <h4>
                    <b>
                        ${subject}
                    </b>
                </h4>
                <div>
                    <div style="max-height: 300px; overflow:auto;">
                    <pre>
                        ${emails[subject]}
                    </pre>
                    </div>
                </div>
            </div>
        </#list>
    </div>

    <div class="footer">
        <p>This message was automatically generated by Loschmidt laboratories middleware. Please do not reply
            directly recipient this email address. If you got any difficulties accessing the system or understanding
            this message, please <a href="mailto: kamil.triscik@gmail.com">system admin</a>.</p>

    </div>
</div>
</body>
</html>